apiVersion: v1
kind: Service
metadata:
  name: prom-service
  namespace: prometheus
spec:
  selector:
    app: prom-app
  type: NodePort
  ports:
  - name: metrics
    port: 5000
    targetPort: 5000
    nodePort: 30900
