apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logger-pvc
  namespace: prometheus
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage