apiVersion: v1
kind: Service
metadata:
  name: logger-service
  namespace: prometheus
spec:
  selector:
    app: logger-app
  type: NodePort
  ports:
  - port: 9050
    targetPort: 9050
    nodePort: 30801